### ISSUE TITLE
upload an opam release

### ISSUE THREAD

**Issue by avsm** [gildor478/ocaml-debian-formats#1]
This would be very useful for me to automate some of the Ubuntu PPAs use in OPAM CI testing (at https://launchpad.net/~avsm).  Any chance of a release into OPAM with a tagged release? Thanks!

**Comment by gildor478** [comment]
Release:
https://forge.ocamlcore.org/frs/?group_id=358

I have also pushed a tag 0.1.0. As for the OPAM release, I don't have time to figure out how to do it. Feel free to upload it if you have time (@edwintorok has pushed a opam/ directory that should contain the required files).
